context:
  version: 0.4.0

package:
  name: jp_tools
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/j/jp_tools/jp_tools-${{ version }}.tar.gz
  sha256: 80d39565eb20b78a04d01e295388eb8e113596e52fda4c935b006e25d5b3d4a6

build:
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
    - jp-utils = jp_tools:main
  noarch: python

requirements:
  host:
  - python >=3.11
  - hatchling
  - pip
  run:
  - python >=3.11
  - requests >=2.32.5
  - tqdm >=4.67.1
  # - numpy >=2.3.4 # extra == "extra"
  # - pandas >=2.3.3 # extra == "extra"
  # - polars >=1.35.2 # extra == "extra"

tests:
- python:
    imports:
    - jp_tools
    pip_check: true

about:
  summary: A simple download hellper to pull files
  description: ''
